name: Manual Tweet Fetch

on:
  workflow_dispatch:
    inputs:
      twitter_handle:
        description: 'Twitter handle to check (without the @)'
        required: true
        default: 'ELDENRING'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run Tweet Scraper for Manual Input
        # Use the handle provided by the user in the input field
        run: node scraper.js ${{ github.event.inputs.twitter_handle }}
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      - name: Commit and Push Log Files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add log/
          git diff --staged --quiet || (git commit -m "Update tweet logs" && git push)
